export const ProductsData = [
  {
    id: 1,
    img: "images/hawaiian.jpg",
    alt: "pizza2",
    name: "Hawaiian ",
    desc: "Pizza sauce, mozzarella, ham, pineapple",
    price: "$9.99",
  },
  {
    id: 2,
    img: "images/hawaiian.jpg",
    alt: "pizza2",
    name: "Hawaiian ",
    desc: "Pizza sauce, mozzarella, ham, pineapple",
    price: "$9.99",
  },
  {
    id: 3,
    img: "images/hawaiian.jpg",
    alt: "pizza2",
    name: "Hawaiian ",
    desc: "Pizza sauce, mozzarella, ham, pineapple",
    price: "$9.99",
  },
  {
    id: 4,
    img: "images/hawaiian.jpg",
    alt: "pizza2",
    name: "Hawaiian ",
    desc: "Pizza sauce, mozzarella, ham, pineapple",
    price: "$9.99",
  },
  {
    id: 5,
    img: "images/hawaiian.jpg",
    alt: "pizza2",
    name: "Hawaiian ",
    desc: "Pizza sauce, mozzarella, ham, pineapple",
    price: "$9.99",
  },
  {
    id: 5,
    img: "images/hawaiian.jpg",
    alt: "pizza2",
    name: "Hawaiian ",
    desc: "Pizza sauce, mozzarella, ham, pineapple",
    price: "$9.99",
  },
];
